### ISSUE TITLE
command line bug

### ISSUE THREAD

**Issue by OwenTZC** [DissectMalware/pyOneNote#6]
here lost “OUTPUT_DIR”
in main.py line 107~114

    output_dir = "./"

    if len(sys.argv) == 3:
        output_dir = sys.argv[2]

    extension = ""
    if len(sys.argv) == 4:
        extension = sys.argv[3]

if it should be:

    output_dir = "./"

    if len(sys.argv) >= 3:
        output_dir = sys.argv[2]

    extension = ""
    if len(sys.argv) == 4:
        extension = sys.argv[3]

or:

    output_dir = "./"

    if len(sys.argv) == 3:
        output_dir = sys.argv[2]

    extension = ""
    if len(sys.argv) == 4:
        output_dir = sys.argv[2]
        extension = sys.argv[3]

**Comment by OwenTZC** [comment]
or there's some command line parser that you could use to parse command lines

**Comment by doomedraven** [comment]
https://github.com/DissectMalware/pyOneNote/pull/7

**Comment by OwenTZC** [comment]
DONE

**Comment by DissectMalware** [comment]
Merged with main
